[package]
name = "dbus-native"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus-native-channel = { path = "../dbus-native-channel" }
dbus-strings = { path = "../dbus-strings" }
libc = "0.2.66"
